### ISSUE TITLE
[metrics] Weird account of steps

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/the-law-factory-parser#109]
While looking for the text with the most steps, I realized metrics.csv accounts only 15 steps instead of 18 for [ppl09-682](https://www.lafabriquedelaloi.fr/articles.html?loi=ppl09-682), while it counts correctly 17 for [ppl15-461](https://www.lafabriquedelaloi.fr/articles.html?loi=ppl15-461).

**Comment by mdamien** [comment]
It's because we count only `hemicycle` (as **2 steps**, even for `lect. def`) and `CMP commission` steps, ignoring the `depot`, `constitutionalité` and `CMP hemicycle` steps.

cf. the code:

```python
def custom_number_of_steps(steps):
    # count the number of columns minus CMP hemicycle
    c = 0
    for step in steps:
        if step.get('stage') == 'CMP':
            if step['step'] == 'commission':
                c += 1
        elif step.get('step') == 'hemicycle':
            c += 2
    return c
```

Not sure if this metrics makes so much sense but adding it to `compute_stats` (#91) will at least tell us what to expect.

**Comment by boogheta** [comment]
retrospectively, I guess this formula is really weird, I think we want as well an indicator of how many steps corresponding to those displayed in the-law-factory, and maybe keep also this one but change it slightly so that each "lecture" within a room counts as 1 and the whole CMP as 1 as well, let's rediscuss it with Olivier on the 20th maybe

**Comment by mdamien** [comment]
This metric has been replaced with `Nombre de textes produits` and `Nombre de dépôts dans les institutions`
