### ISSUE TITLE
[articles] parsing fails when numbering is added

### ISSUE THREAD

**Issue by njoyard** [regardscitoyens/the-law-factory-parser#60]
An error `could not retrieve II` happens in `generate_data.sh` with the following configuration:

**Article X at step N-1**

```
bar
```

**Article X at step N**

```
I. foo
II. (unchanged)
III. baz
```

Example here:
- step N-1: http://www.senat.fr/leg/pjl15-662.html#B2825835408
- step N: http://www.senat.fr/leg/tas15-161.html#B2825835408

Debug output:

```
DEBUG: get back Art 43 bis
EXTRACT non-modifiés for 43 ter: II
- GET Extract from II to 
    TEST: Au premier alinéa de l'article L. 5214-3-1 du code
ERROR: could not retrieve II
ERROR completing ../../data/pjl15-nouvelles_libertes_entreprises_actifs/.tmp/html/http%3A%2F%2Fwww.senat.fr%2Fleg%2Ftas15-161.html
```

**Comment by njoyard** [comment]
Same issue here:
* step N-1: http://www.senat.fr/leg/ppl15-519.html#B2506700443
* step N: http://www.senat.fr/leg/tas15-148.html#B2506700443

with

**Article 11 at step N-1**
```
bar
```

**Article 11 at step N**
```
I. foo
II. (unchanged)
```

**Comment by mdamien** [comment]
Fixed in https://github.com/regardscitoyens/the-law-factory-parser/commit/9d1a0c9af695cf48537e956bdcf617bb29481766#diff-cc1f1318781d8be1f63611bf5aa1cee0L123 by removing the restriction of the `force` modifier (before it was done only for Article 1).

How it works: if alinea II is not found at step N-1, it copy all the previous article.
And there's a protection to do this only one time per article.
