### ISSUE TITLE
parse_texte.py as a Python module

### ISSUE THREAD

**Issue by promethe42** [regardscitoyens/the-law-factory-parser#62]
Hi,

I refactored [parse_texte.py](https://github.com/regardscitoyens/the-law-factory-parser/blob/master/scripts/collectdata/parse_texte.py) so it can be used as a Python module:

https://github.com/Legilibre/duralex/blob/master/duralex/bill_parser.py

I've also added a [fix](https://github.com/Legilibre/duralex/blob/master/duralex/bill_parser.py#L363).

I'd like to make sure we don't maintain two separate versions.
So I'd like to make a PR for this new version to be merged here.
Then I would make DuraLex depend on a the-law-factory-parser pip package.

So two questions:

* would you be interested in such a pull request?
* is there a the-law-factory-parser pip package? otherwise, how should I handle the dependency between our two projects ? I'm guessing I should git clone it at the root of the DuraLex projet and update it manually... or use a git submodule ?

Thanks!

**Comment by njoyard** [comment]
Yep, very interested IMO. We're planning to do a bunch of code cleanup and refactoring soon-ish so every helping hand is appreciated.

There is no pip package, and (again IMO) it would not really be useful. There is no clear interface to the package, and publishing it would imply there is some (as well as enough documentation).

I'd be more inclined to do one of the following:
* Have *you* publish a duralex package, and have tlf-parser use it as a dependency. That would seem logical as duralex seems intended to be used by law-related projects.
* Have a 3rd package (say french-law-awesome-parsing-tools-of-death) that we both depend on.

As I said, we're planning to do a bunch of refactoring, so maybe waiting for that would be the wisest option. In the meantime, I think you can specify a git url in your requirements file to depend on tlf-parser without publication on pypi.

**Comment by RouxRC** [comment]
Hey there,
Thanks for all this @promethe42, it's really cool :)
I agree with @njoyard, as such publishing tlf-parser on pip would be quite weird. Externalising the text parser, either in duralex's pip package, or in a dedicated lib repository we would share sounds good to me.
In the mean time, a PR just on the diffed parser file makes sense in any case.

**Comment by promethe42** [comment]
So I could keep my version of parse_texte.py and add a command line option to exit its content before any further processing.

Then I publish a duralex pip package for you to depend on.

OK ?

**Comment by davidbgk** [comment]
Additional question: is the fix mentioned in the first comment currently present in this repository version? It [looks to be the case](https://github.com/regardscitoyens/the-law-factory-parser/blob/master/tools/parse_texte.py#L623-L631) but I'm unsure about the logic that has been fixed so I prefer to double check with instigators :)

**Comment by RouxRC** [comment]
I believe @promethe42 ended up copying it on his side as a result of the apathy of the project at the time, our bad... It has changed quite a lot thanks to @mdamien's work over the past few months and could probably be "remerged".

Although we haven't put efforts into packaging this particular function yet, partly because using parse_texte.py on its own is only relevant for initial texts versions (PPJL & PJL). For all following versions, the parsed result needs to be completed further on with complete_articles.py using the text of previous versions, which is among over things what parse_one.py does for a whole dossier using parse_doslegs_texts.py.

The best would probably be make this repo a package with its main scripts executables for some atomic tasks such as in senapy or anpy. Contributions very welcome ;)
