### ISSUE TITLE
Missing `end` date triggering weird bug

### ISSUE THREAD

**Issue by boogheta** [regardscitoyens/the-law-factory-parser#95]
Werid last step + missing institution for pjl11-152 + pjl11-153 + pjl11-134

![image](https://user-images.githubusercontent.com/1469823/44671764-b3fd4800-aa26-11e8-8bd0-53e2edcc5d30.png)

**Comment by mdamien** [comment]
After some investigation, this bug is very nice:

 - javascript is crashing because we try to display the promulgation step (with a `step` attribute set a null)
 - the promulgation step should not be shown but there is a `debats_order` attribute
 - the `debats_order` is there because we detect it as the currently debated step in update_procedure.py
 - it's detected as the current step because there's no `end` date for the procedure (also a bug since the procedure has an `url_jo`)

So, I'm doing a PR fixing all those little things

**Comment by mdamien** [comment]
Fixed in https://github.com/regardscitoyens/the-law-factory-parser/commit/61845d379e5391de203e52814a09eead26de9246

- https://www.lafabriquedelaloi.fr/articles.html?loi=pjl11-152
- https://www.lafabriquedelaloi.fr/articles.html?loi=pjl11-153
- https://www.lafabriquedelaloi.fr/articles.html?loi=pjl11-134
